# Generated by Django 2.2.6 on 2019-10-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='car',
            field=models.CharField(max_length=60),
        ),
    ]
